### ISSUE TITLE
Intermittent connection timeout error when executing facts gathering script

### ISSUE THREAD

**Issue by timblaktu** [wcm-io-devops/ansible-jenkins-facts#6]
I have intermittently gotten this error in this task:

```
TASK [wcm_io_devops.jenkins_facts : gather_jenkins_facts : execute gather script on jenkins instance.] ***
fatal: [jmtest3]: FAILED! => changed=false
  msg: 'HTTP error -1 Connection failure: timed out'
  output: ''
```

I am not sure what if anything I have done to cause the error to start happening, but when I revert my jenkins master VM to a pre-provisioning snapshot and rerun the playbook, the error does not happen. 

I will post more info here if I see a pattern of when this occurs. I suspect it's something I'm doing with CasC. 

Let me know if anything jumps out at you and ignore if not. Thanks.

**Comment by tobias-richter** [comment]
@timblaktu it is hard to support here since I am not able to debug it on my own. The timeout issue may occur when your jenkins instance is not running or takes long time to answer. I suggest to run ansible in verbose-mode (-v, -vv, -vvv or even more) and check what is happening here.

Please checkout the documentation and adjust the timeout values:  `jenkins_facts_script_timeout` `jenkins_facts_uri_timeout`.
